server:
  port: 7071
spring:
  application:
    name: ms-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Cristian-Mamani/FILTRASION-ULTIMO.git # ruta del repositorio git
          searchPaths: config-data
          default-label: circuitbreaker
  security:
    user:
      name: root
      password: 123456